### ISSUE TITLE
Does not read anything

### ISSUE THREAD

**Issue by vekexasia** [gytisgreitai/zehnder-can-mqtt#1]
Hey, i'm trying to get this to work. it looks like it does not read anything from the can interface. 

I modified the script to use ttyACM0 and 115200 as in zcan project but it does not seem to read anything. 

zcan show --all --debug seems to dump stuff.

**Comment by gytisgreitai** [comment]
Sorry, missed this issue, but I guess you sorted everything out :)

**Comment by vekexasia** [comment]
Yes sorry, thanks for your time and efforts :) reading through the code helped me a lot.
